### ISSUE TITLE
Error when using `docker-compose` to quick start.

### ISSUE THREAD

**Issue by dooglio** [lhartikk/naivechain#7]
Here is what happens when I try:

```
$ docker-compose up
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

```

I'm running Ubuntu 16.04 Linux, by the way. My `docker-compose` package is at version `1.5.2-1`.

**Comment by dooglio** [comment]
Here is my `docker-compose.yaml` file (the one that comes stock in the git archive):
```
version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
  node2:
    environment:
      - PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    links:
      - node1:node1
  node3:
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    links:
      - node2:node2

```
